---
title: "DEG_RNA_summary"
author: "LD"
date: "2025-01-19"
output: html_document
---


```{r setup}
library(gprofiler2)
library(plyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(cowplot)

dir_out <- "/home/common/data/output/projects/ENDO/E044/A031/"
setwd(dir_out)
```


Determine inflection point based on unfiltered DEGs
```{r}
##Combine muscat output into one dataframe
PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/A030"), pattern = "res_mm_dream.rds", recursive = TRUE, full.names = TRUE)
RNAlistRDS <- lapply(PATHS, readRDS)
names(RNAlistRDS) <- print(PATHS)
RNAlistRDS <- unlist(RNAlistRDS, recursive = FALSE) #combine sub-lists
RNAlistRDS <- lapply(RNAlistRDS,plyr::rbind.fill)
RNAlistRDSdf <- as.data.frame(do.call(rbind, RNAlistRDS))

##exclude ribosomal genes (comment: does not change the inflection point)
rb.genes_DEGs <- unique(grep(pattern = "^RP[SL]", RNAlistRDSdf$gene, value=TRUE)) #around 150 unique rb genes
RNAlistRDSdf <- RNAlistRDSdf[!(RNAlistRDSdf$gene %in% rb.genes_DEGs), ]

##Determine inflection point
#Determine Inflection Point, No log2 scale, bw = 0.02
plot(density(RNAlistRDSdf$AveExpr))
# Create the density plot and store it in an object
density_plot <- density(RNAlistRDSdf$AveExpr, bw = 0.02) #good values 0.025 or 0.02, 0.01 is too small
plot(density_plot)
# Calculate the second derivative of the density curve
second_derivative <- diff(diff(density_plot$y)) / diff(density_plot$x)^2
# Find where the second derivative crosses zero (inflection point)
inflection_points <- density_plot$x[which(diff(sign(second_derivative)) != 0)]
# Print or plot the inflection point(s)
cat("Inflection Point(s):", inflection_points, "\n")
# You can also plot the density curve with the inflection point(s) marked
plot(density_plot)
abline(v = inflection_points, col = "red", lty = 2)
abline(v = 18.53202, col = "green", lty = 2)
text(x=18.45, y=1.5, srt=90, '18.53202')

#Best result: no log2 scale, bw = 0.02 with resulting inflection point 18.53202

length(RNAlistRDSdf$gene)
RNAlistRDSdf_filt <- RNAlistRDSdf %>% dplyr::filter(AveExpr > 18.53202) 
length(RNAlistRDSdf_filt$gene)
```

summarize DEGs into df and plot
```{r RNA assay}
#RNA assay
PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/A030"), pattern = "res_mm_dream.rds", recursive = TRUE, full.names = TRUE)
print(PATHS)
RNAlistRDS <- lapply(PATHS, readRDS)
names(RNAlistRDS) <- print(PATHS)
RNAlistRDS <- unlist(RNAlistRDS, recursive = FALSE) #combine sub-lists
RNAlistRDS <- lapply(RNAlistRDS,plyr::rbind.fill)
RNAlistRDSdf <- as.data.frame(do.call(rbind, RNAlistRDS))
RNAlistRDS005 <- lapply(RNAlistRDS, function(x) dplyr::filter(x, p_adj.loc < 0.05))
RNAlistRDS005 <- as.data.frame(do.call(rbind, RNAlistRDS005))
#Check for cluster_ids that have or don't have DEGs with p_adj.loc < 0.05
intersect(levels(factor(RNAlistRDSdf$cluster_id)),levels(factor(RNAlistRDS005$cluster_id)))
setdiff(levels(factor(RNAlistRDSdf$cluster_id)),levels(factor(RNAlistRDS005$cluster_id)))
#Add columns stage, clustering, annotation_reference
library(stringr)
RNAlistRDS005 <- RNAlistRDS005 %>%
  dplyr::mutate(stage = case_when(
    str_detect(rownames(RNAlistRDS005), "_severe") ~ "severe",
    str_detect(rownames(RNAlistRDS005), "_mild") ~ "mild",
    TRUE ~ "all"
  ))
RNAlistRDS005 <- RNAlistRDS005 %>%
  dplyr::mutate(clustering = case_when(
    str_detect(rownames(RNAlistRDS005), "major") ~ "major",
    str_detect(rownames(RNAlistRDS005), "united") ~ "united",
    TRUE ~ "RefinedCluster"
  ))
RNAlistRDS005 <- RNAlistRDS005 %>%
  dplyr::mutate(annotation_reference = case_when(
    str_detect(rownames(RNAlistRDS005), "Tan") ~ "Tan",
    str_detect(rownames(RNAlistRDS005), "Fonseca") ~ "Fonseca"
  ))

length(unique(RNAlistRDS005$gene)) #12115

write.csv(RNAlistRDS005,"/home/common/data/output/projects/ENDO/E044/A031/RNAlistRDS005_unmerged.csv")
#RNAlistRDS005 <- read.csv("/home/common/data/output/projects/ENDO/E044/A031/RNAlistRDS005_unmerged.csv", row.names = 1)

```


gProfiler based on RNA/SCT assay and per annotation with gene expression >18.53202
```{r}
##function to run gProfiler and save output
gProfiler_FUN <- function(x,ANALYSIS,GRADE,ORDERED_QUERY,ASSAY,dir_out) {
#gProfiler
custom_bg <- unique(x$gene)
query <- x %>%
  dplyr::filter(AveExpr > 18.53202) %>%
  dplyr::filter(p_adj.loc < 0.05) %>%
  dplyr::arrange(p_adj.loc) #arrange by lowest p_adj.loc
if(nrow(query) > 0){
query <- distinct(query, gene, .keep_all= TRUE) #remove duplicates of gene with higher p_adj.loc
query <- query$gene
gostres <<- gost(query = query, 
                organism = "hsapiens", 
                ordered_query = ORDERED_QUERY, #can use TRUE, p_adj.loc has been arranged 
                multi_query = FALSE, 
                significant = TRUE, #only statistically significant results should be returned
                exclude_iea = FALSE, 
                measure_underrepresentation = FALSE, 
                evcodes = TRUE,
                user_threshold = 0.05, 
                correction_method = "g_SCS", #g_SCS is default
                domain_scope = "annotated", #if custom_bg is set, I believe this shouldn't matter too much
                custom_bg = custom_bg, #custom background, use!
                numeric_ns = "", 
                sources = NULL, #by default all sources are analyzed
                as_short_link = FALSE)
if(length(gostres) > 0){
results <- gostres$result
results$cluster_id <- levels(as.factor(x$cluster_id))
results$analysis <- print(ANALYSIS)
results$assay <- print(ASSAY)
results$grade <- print(GRADE) 
results$ordered_query <- print(ORDERED_QUERY)
results$parents <- NULL
write.csv(results,paste0("gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".csv"))
print(paste0("Saved gotres as gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".csv"))
plot <- gostplot(gostres, capped = TRUE, interactive = FALSE) + ggtitle(paste0("gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY)))
ggsave(plot = plot, filename = paste0(dir_out,"gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".png"), width = 7, height = 5)
print("Saved plot")
}
}
}
##function to run gProfiler_FUN on different grades, analysis and assay
RUN_gProfier <- function(GRADE, ANALYSIS,ASSAY,SPECIFICATION){
dir_out <- paste0("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044",ANALYSIS,"/",ASSAY,"assay_",SPECIFICATION,"/")
dir.create(dir_out, recursive = TRUE)
setwd(dir_out)
#Read paths to DEG output .rds files
if (ASSAY == "RNA") { 
    PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/",ANALYSIS), pattern = "res_mm_dream.rds", recursive = TRUE, full.names = TRUE)
    } else if (ASSAY == "SCT") {
    PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/",ANALYSIS), pattern = "mm_dream_sct_counts_all.rds", recursive = TRUE, full.names = TRUE)
    }
#Select paths based on all/mild/severe
if (GRADE == "all") { 
    PATHS <- PATHS[!grepl("_severe", PATHS)]
    PATHS <- PATHS[!grepl("_mild", PATHS)]
    print(PATHS)
    } else if (GRADE == "mild") {
    PATHS <- PATHS[grepl("_mild", PATHS)]
    print(PATHS)
    } else if  (GRADE == "severe") {
    PATHS <- PATHS[grepl("_severe", PATHS)]
    print(PATHS)
    } 
RNAlistRDS <- lapply(PATHS, readRDS)
RNAlistRDS <- unlist(RNAlistRDS, recursive = FALSE) #combine sub-lists
RNAlistRDS <- RNAlistRDS[!duplicated(RNAlistRDS)]
lapply(RNAlistRDS, gProfiler_FUN, ANALYSIS = ANALYSIS,GRADE = GRADE,ORDERED_QUERY = FALSE, ASSAY = ASSAY, dir_out = dir_out)
lapply(RNAlistRDS, gProfiler_FUN, ANALYSIS = ANALYSIS,GRADE = GRADE,ORDERED_QUERY = TRUE, ASSAY = ASSAY, dir_out = dir_out)
}

RUN_gProfier(GRADE = "all", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "severe", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "mild", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "all", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "severe", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "mild", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
```

##Ongoing xxxx
gProfiler based on RNA assay and per annotation with gene expression >18.53202 and BH pval adjusted
```{r}
##function to run gProfiler and save output
gProfiler_FUN <- function(x,ANALYSIS,GRADE,ORDERED_QUERY,ASSAY,dir_out) {
#gProfiler
custom_bg <- unique(x$gene)
query <- x %>%
  dplyr::filter(AveExpr > 18.53202) %>%
  dplyr::filter(p_adj.loc < 0.05) %>%
  dplyr::arrange(p_adj.loc) #arrange by lowest p_adj.loc
if(nrow(query) > 0){
query <- distinct(query, gene, .keep_all= TRUE) #remove duplicates of gene with higher p_adj.loc
query <- query$gene
gostres <<- gost(query = query, 
                organism = "hsapiens", 
                ordered_query = ORDERED_QUERY, #can use TRUE, p_adj.loc has been arranged 
                multi_query = FALSE, 
                significant = TRUE, #only statistically significant results should be returned
                exclude_iea = FALSE, 
                measure_underrepresentation = FALSE, 
                evcodes = TRUE,
                user_threshold = 0.05, 
                correction_method = "g_SCS", #g_SCS is default
                domain_scope = "annotated", #if custom_bg is set, I believe this shouldn't matter too much
                custom_bg = custom_bg, #custom background, use!
                numeric_ns = "", 
                sources = NULL, #by default all sources are analyzed
                as_short_link = FALSE)
if(length(gostres) > 0){
results <- gostres$result
results$cluster_id <- levels(as.factor(x$cluster_id))
results$analysis <- print(ANALYSIS)
results$assay <- print(ASSAY)
results$grade <- print(GRADE) 
results$ordered_query <- print(ORDERED_QUERY)
results$parents <- NULL
write.csv(results,paste0("gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".csv"))
print(paste0("Saved gotres as gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".csv"))
plot <- gostplot(gostres, capped = TRUE, interactive = FALSE) + ggtitle(paste0("gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY)))
ggsave(plot = plot, filename = paste0(dir_out,"gProfiler_",ANALYSIS,"_",GRADE,"_",levels(as.factor(x$cluster_id)),"_OrderedQuery",as.character(ORDERED_QUERY),".png"), width = 7, height = 5)
print("Saved plot")
}
}
}
##function to run gProfiler_FUN on different grades, analysis and assay
RUN_gProfier <- function(GRADE, ANALYSIS,ASSAY,SPECIFICATION){
dir_out <- paste0("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044",ANALYSIS,"/",ASSAY,"assay_",SPECIFICATION,"/")
dir.create(dir_out, recursive = TRUE)
setwd(dir_out)
#Read paths to DEG output .rds files
if (ASSAY == "RNA") { 
    PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/",ANALYSIS), pattern = "res_mm_dream.rds", recursive = TRUE, full.names = TRUE)
    } else if (ASSAY == "SCT") {
    PATHS <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/",ANALYSIS), pattern = "mm_dream_sct_counts_all.rds", recursive = TRUE, full.names = TRUE)
    }
#Select paths based on all/mild/severe
if (GRADE == "all") { 
    PATHS <- PATHS[!grepl("_severe", PATHS)]
    PATHS <- PATHS[!grepl("_mild", PATHS)]
    print(PATHS)
    } else if (GRADE == "mild") {
    PATHS <- PATHS[grepl("_mild", PATHS)]
    print(PATHS)
    } else if  (GRADE == "severe") {
    PATHS <- PATHS[grepl("_severe", PATHS)]
    print(PATHS)
    } 
RNAlistRDS <- lapply(PATHS, readRDS)
RNAlistRDS <- unlist(RNAlistRDS, recursive = FALSE) #combine sub-lists
RNAlistRDS <- RNAlistRDS[!duplicated(RNAlistRDS)]
lapply(RNAlistRDS, gProfiler_FUN, ANALYSIS = ANALYSIS,GRADE = GRADE,ORDERED_QUERY = FALSE, ASSAY = ASSAY, dir_out = dir_out)
lapply(RNAlistRDS, gProfiler_FUN, ANALYSIS = ANALYSIS,GRADE = GRADE,ORDERED_QUERY = TRUE, ASSAY = ASSAY, dir_out = dir_out)
}

RUN_gProfier(GRADE = "all", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "severe", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "mild", ANALYSIS = "A030", ASSAY = "RNA",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "all", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "severe", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
RUN_gProfier(GRADE = "mild", ANALYSIS = "A030", ASSAY = "SCT",SPECIFICATION = "PerAnnotation_AveExpr18_53202")
```



```{r Combine output tables from gProfiler}
#functions
summarize_gProfiler_PerAnnotation <- function(x){
ASSAY = "A030"
##Combine all results
gProfilerlist <- list.files(path = paste0("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044",ASSAY,"/",x), pattern = "TRUE.csv$|FALSE.csv$", full.names = TRUE)
gProfilerlist <- lapply(gProfilerlist, read.csv) #read .rds
#Combine all gProfiler results into one df, save
gProfiler <- plyr::rbind.fill(gProfilerlist) #bind deg lists into one df
gProfiler$specification <- print(x)
#save csv
write.csv(gProfiler, paste0("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044",ASSAY,"/gProfiler_",ASSAY,"_",x,"_summary.csv"))
table(gProfiler$grade)
#table(gProfiler$cluster_id,gProfiler$grade)
}

ASSAY = "A030"
DIRSLIST <- list.dirs(path = paste0("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044",ASSAY),full.names = FALSE)
DIRSLIST_Merged <- DIRSLIST[grepl("Merged", DIRSLIST)]
DIRSLIST_PerAnnotation <- DIRSLIST[grepl("PerAnnotation", DIRSLIST)]
lapply(DIRSLIST_PerAnnotation,summarize_gProfiler_PerAnnotation)
```



```{r setup}
library(ggplot2)
library(dplyr)
library(purrr)
library(Seurat)
library(tidyr)
library(ggrepel)

dir_out <- "/home/common/data/output/projects/ENDO/E044/A031/InterestingDEGs/AveExpr18_53202/"
dir.create(dir_out, recursive = TRUE)
```

```{r}
###Read in gProfiler_A030_RNAassay_PerAnnotation_AveExpr18_53202_summary and filter for Tan annotation
gProfiler_df <- read.csv("/home/common/data/output/projects/ENDO/E044/A031/gProfiler/E044A030//gProfiler_A030_RNAassay_PerAnnotation_AveExpr18_53202_summary.csv")
gProfiler_df <- gProfiler_df %>% dplyr::filter(source != "HPA") #HPA is pretty useless for our analysis
Tan_clusters <- read.csv("/home/common/data/output/projects/ENDO/E044/A031/RNAlistRDS005_unmerged.csv") %>%
  filter(annotation_reference == "Tan") %>%
  distinct(cluster_id) %>%
  pull()
gProfiler_df <- gProfiler_df %>% 
  filter(cluster_id %in% Tan_clusters)

###interesting term_names
#Immune System and inflammation
ImmuneTermsGREP <- c("TGF", "TNF", "NOD", "IL-", "immun", "cytokine", "chemokine", "NF-kappa")
ImmuneTerms <- gProfiler_df %>%
  filter(grepl(paste(ImmuneTermsGREP, collapse = "|"), term_name, ignore.case = TRUE)) %>% 
  pull(term_name) %>% 
  unique()
#angiogenesis
angiogenesisTerms  <- c(unique(gProfiler_df$term_name[grepl("VEGF", gProfiler_df$term_name, ignore.case = TRUE)]),
                       unique(gProfiler_df$term_name[grepl("angiog", gProfiler_df$term_name, ignore.case = TRUE)]))
#extracellullar terms
extracellularTerms <- unique(gProfiler_df$term_name[grepl("extracellular", gProfiler_df$term_name, ignore.case = TRUE)])
#cell adhesion
adhesionTermsGREP <- c("adhesion", "junction")
adhesionTerms <- gProfiler_df %>%
  filter(grepl(paste(adhesionTermsGREP, collapse = "|"), term_name, ignore.case = TRUE)) %>% 
  pull(term_name) %>% 
  unique()
#growth factors
insulinTerms <- unique(gProfiler_df$term_name[grepl("insulin", gProfiler_df$term_name, ignore.case = TRUE)])
#Other interesting terms
otherTerms <- c('CTNNB1-DDX5-HDGF complex') #Hepatoma-Derived Growth Factor and DDX5 Promote Carcinogenesis and Progression of Endometrial Cancer by Activating β-Catenin
# Define the list of interesting terms
interesting_terms <- list(
  ImmuneTerms = ImmuneTerms,
  AngiogenesisTerms = angiogenesisTerms,
  ExtracellularTerms = extracellularTerms,
  AdhesionTerms = adhesionTerms,
  InsulinTerms = insulinTerms
  #,OtherTerms = otherTerms
)
# Loop through the list and assign categories
gProfiler_df$DEG_category <- NA
for (category_name in names(interesting_terms)) {
  terms <- interesting_terms[[category_name]]
  for (term in terms) {
    gProfiler_df$DEG_category[gProfiler_df$term_name == term] <- category_name
  }
}
table(gProfiler_df$DEG_category)



gProfiler_df %>% 
  #dplyr::select(p_value, term_size, query_size, intersection_size, term_id, term_name) %>% 
  dplyr::filter(term_size > 25 & term_size < 750) %>% #larger terms are likely to be excessively broad and prone to false positives
  distinct(cluster_id,analysis,assay,grade,term_name, .keep_all = TRUE) %>%
  #filter(grade == "all")  %>%
  filter(!grepl(pattern = "HPA|HP|CORUM|MIRNA", x = term_id)) %>%
  dplyr::arrange(p_value) %>% 
  #dplyr::slice_head(n = 20) %>% 
  ggplot2::ggplot() + 
  ggplot2::aes(y = reorder(term_name, -log(p_value)), x = -log(p_value), color = grade, size = intersection_size/term_size * 100) + #, shape = ordered_query
  ggplot2::geom_point() + 
  #ggplot2::scale_color_continuous(name = "-Log(adj. p-value)") + 
  ggplot2::scale_size_continuous("Intersection size / Term size * 100 (%)") + 
  ggplot2::theme_classic() + 
  ggplot2::xlab("-Log(adj. p-value)") + 
  ggplot2::ylab("enriched terms") + 
  ggplot2::ggtitle("all cells")
ggsave(paste0(dir_out, "GOterms_all_severe.pdf"),
  plot = last_plot(),
  width = 14, height = 14)

#save Table
gProfiler_df_save <- gProfiler_df %>% 
  #dplyr::select(p_value, term_size, query_size, intersection_size, term_id, term_name) %>% 
  #dplyr::filter(term_size > 25 & term_size < 750) %>% #larger terms are likely to be excessively broad and prone to false positives
  distinct(cluster_id,analysis,assay,grade,term_name, .keep_all = TRUE) %>%
  #filter(grade == "all")  %>%
  #filter(!grepl(pattern = "HPA|HP|CORUM|MIRNA", x = term_id)) %>%
  dplyr::arrange(p_value)
table(gProfiler_df_save$term_id)
write.csv(gProfiler_df_save, paste0(dir_out, "GOterms_all_severe_minimalfiltering.csv"))


######
##GO plot with cell type label
gProfiler_df %>% 
  #dplyr::select(p_value, term_size, query_size, intersection_size, term_id, term_name) %>% 
  dplyr::filter(term_size > 25 & term_size < 750) %>% #larger terms are likely to be excessively broad and prone to false positives
  distinct(cluster_id,analysis,assay,grade,term_name, .keep_all = TRUE) %>%
  #filter(grade == "all")  %>%
  filter(!grepl(pattern = "HPA|HP|CORUM|MIRNA", x = term_id)) %>%
  dplyr::arrange(p_value) %>% 
  #dplyr::slice_head(n = 20) %>% 
  ggplot2::ggplot() + 
  ggplot2::aes(y = reorder(term_name, -log(p_value)), x = -log(p_value), color = cluster_id, size = intersection_size/term_size * 100) + #, shape = ordered_query
  ggplot2::geom_point() + 
  #ggplot2::scale_color_continuous(name = "-Log(adj. p-value)") + 
  ggplot2::scale_size_continuous("Intersection size / Term size * 100 (%)") + 
  ggplot2::theme_classic() + 
  ggplot2::xlab("-Log(adj. p-value)") + 
  ggplot2::ylab("enriched terms") + 
  ggplot2::ggtitle("all cells")
ggsave(paste0(dir_out, "GOterms_all_severe_colorCellID.pdf"),
  plot = last_plot(),
  width = 14, height = 14)

##############################################################################################################################
##Merge the DEG table with the Terms 

#RNA assay DEGs from proliferative samples
RNAlistRDS005_df <- read.csv("/home/common/data/output/projects/ENDO/E044/A031/RNAlistRDS005_unmerged.csv") %>%
  filter(annotation_reference == "Tan") %>%
  filter(AveExpr > 18.53202)
##Exclude Haemoglobin genes, mitochondrial genes, #ribosomal genes
hb.genes <- c("HBA1","HBA2","HBB","HBG2","HBG1","HBD","HBE1","HBZ")#haemoglobin genes, there are no hb genes in the DEG list
mt.genes <- grep("^MT-", RNAlistRDS005_df$gene, value=TRUE)#mitochondrial genes, no genes
rb.genes <- grep(pattern = "^RP[SL]", RNAlistRDS005_df$gene, value=TRUE)#ribosomal genes, 165 genes
RNAlistRDS005_df <- RNAlistRDS005_df %>%
  dplyr::filter(!gene %in% rb.genes) #Focus on protein coding genes

#Mutate so each row contains only a single gene in the "gene" column
gProfiler_df <- gProfiler_df %>%
  mutate(gene = strsplit(intersection, ",")) %>%
  unnest(gene) %>%
  dplyr::rename(stage = grade) %>%
  dplyr::filter(assay == "RNA")

# left_join RNAlistRDS005_df with Terms by c("cluster_id", "gene", "stage"), no multiple match warning
result_df <- left_join(RNAlistRDS005_df, gProfiler_df, by = c("cluster_id", "gene","stage"))

###Plot DEGs
# Create vulcano plot
ggplot(result_df, aes(x = logFC, y = -log10(p_adj.loc))) +
  geom_point(data = result_df, aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = result_df %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"),
             aes(color = DEG_category), size = 2) +
  theme_minimal() +
  facet_wrap(~stage)
ggsave(filename = paste0(dir_out, 'vulcano_DEG_category_InterestingTerms.pdf'), width =8,height=6)

# Create vulcano plot with gene labels
#logFC vs AveExpr with gene labels
InterestingTerms <- result_df[,c(1:12,34)] %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms") %>% 
  distinct(gene, logFC,AveExpr,p_adj.loc, .keep_all = TRUE) %>% 
  #dplyr::filter(logFC > 0.5 | logFC < -0.5) %>% 
  dplyr::filter(stage == "all", annotation_reference == "Tan", AveExpr > 18.5, logFC > 0.2)
plot <- ggplot(result_df, aes(x = logFC, y = -log10(p_adj.loc))) +
  geom_point(data = result_df, aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = result_df %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"),
             aes(color = DEG_category), size = 2) +
  theme_minimal()+
  ylim(0,18) +
  xlim(-.9,1.2) +
  geom_text_repel(data = InterestingTerms,
                  aes(label = gene),
                  size = 2,
                  max.overlaps = 50,
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50')
plot
ggsave(plot, filename = paste0(dir_out, 'vulcano_DEG_category_InterestingTerms_labelled.pdf'), width =16,height=12)

# Create vulcano plot with gene labels
#logFC vs AveExpr with gene labels
InterestingTerms <- result_df[,c(1:12,34)] %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms") %>% 
  distinct(gene, logFC,AveExpr,p_adj.loc, .keep_all = TRUE) %>% 
  #dplyr::filter(logFC > 0.5 | logFC < -0.5) %>% 
  dplyr::filter(stage == "all", annotation_reference == "Tan", abs(logFC) > 0.5)
result_df_all <- filter(result_df,stage == "all")
ggplot(result_df_all, aes(x = logFC, y = -log10(p_adj.loc))) +
  geom_point(aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = result_df_all %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"),
             aes(x = logFC, y = -log10(p_adj.loc), color = DEG_category), size = 2) +
  theme_minimal() +
  ylim(-2, 17) +
  xlim(-0.9, 1.2) +
  geom_text_repel(data = result_df_all[2:12] %>% dplyr::filter(abs(logFC) > 0.5) %>% distinct(),
                  aes(label = gene),
                  size = 2,
                  max.overlaps = 50,
                  box.padding = 0.35,
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  facet_wrap(~stage)
ggsave(filename = paste0(dir_out, 'vulcano_DEG_category_InterestingTerms_labelledlogFC05.pdf'), width =8,height=6)

results_df_logFC05 <- result_df[2:12] %>% dplyr::filter(abs(logFC) > 0.5) %>% distinct()
write.csv(results_df_logFC05, paste0(dir_out,'TermslogFC05.csv'))

#logFC vs AveExpr
ggplot(result_df, aes(x = log2(AveExpr-17.00183), y = logFC)) +
  geom_point(data = result_df, aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = result_df %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"),
             aes(color = DEG_category), size = 2) +
  theme_minimal() +
  geom_text(data = result_df %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"), aes(label = gene))
ggsave(filename = paste0(dir_out, 'AveExprLOG2_logFC_InterestingTerms.pdf'), width =8,height=6)

#logFC vs AveExpr with gene labels
InterestingTerms <- result_df[,c(1:12,34)] %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms") %>% 
  distinct(gene, logFC,AveExpr,p_adj.loc, .keep_all = TRUE) %>% 
  #dplyr::filter(logFC > 0.5 | logFC < -0.5) %>% 
  dplyr::filter(stage == "all", annotation_reference == "Tan", AveExpr > 18.5)

ggplot(result_df, aes(x = log2(AveExpr-17.00183), y = logFC)) +
  geom_point(data = result_df, aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = InterestingTerms , aes(color = DEG_category), size = 2) +
  theme_minimal() +
  geom_text_repel(data = InterestingTerms,
                  aes(label = gene),
                  size = 2,
                  max.overlaps = 35,
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50')
ggsave(filename = paste0(dir_out, 'AveExprLOG2_logFC_InterestingTerms_labelled.pdf'), width =14,height=8)

#logFC vs AveExpr
ggplot(result_df, aes(x = AveExpr, y = logFC)) +
  geom_point(data = result_df, aes(color = "Non-overlapping"), size = 1, color = "grey") +
  geom_point(data = result_df %>% dplyr::filter(!is.na(DEG_category), DEG_category != "EndometriumTerms"),
             aes(color = DEG_category), size = 2) +
  theme_minimal()
 ggsave(filename = paste0(dir_out, 'AveExpr_logFC_InterestingTerms.pdf'), width =8,height=6)
 
```

```{r Make DotPlots}
#Mutate so each row contains only a single gene in the "gene" column
gProfiler_df <- gProfiler_df %>%
  dplyr::filter(!is.na(DEG_category))
table(gProfiler_df$term_name,gProfiler_df$cluster_id)

table <- left_join(gProfiler_df, RNAlistRDS005_df[,c("gene","logFC","AveExpr","p_adj.loc","cluster_id","stage")], by = c("gene","cluster_id","stage"))

#x = -log(p_adj.loc)
table %>%
  arrange(DEG_category) %>%
  #dplyr::filter(term_name == "extracellular organelle") %>%
  ggplot2::ggplot() + 
  ggplot2::aes(y = reorder(gene, -log(logFC)), x = -log(p_adj.loc), color = stage, size = logFC) + 
  ggplot2::geom_point() + 
  ggplot2::scale_size_continuous("logFC") + 
  ggplot2::scale_x_continuous(limits = c(1, 6)) +
  ggplot2::theme_classic() +
  ggplot2::facet_wrap(~term_name, scales = "free_y", ncol = 13) +
  ggplot2::theme(strip.text = ggplot2::element_text(size = 8))
 ggsave(filename = paste0(dir_out, 'DotPlot_DEGcategories_DEGs_logFC_pval.pdf'), width =25,height=12)
 
#x = p_adj.loc
table %>%
  arrange(DEG_category) %>%
  #dplyr::filter(term_name == "extracellular organelle") %>%
  ggplot2::ggplot() + 
  ggplot2::aes(y = reorder(gene, -log(logFC)), x = p_adj.loc, color = stage, size = logFC) + 
  ggplot2::geom_point() + 
  ggplot2::scale_size_continuous("logFC") + 
  ggplot2::theme_classic() +
  ggplot2::facet_wrap(~term_name, scales = "free_y", ncol = 13) +
  ggplot2::theme(strip.text = ggplot2::element_text(size = 8))

#x = logFC
table %>%
  arrange(DEG_category) %>%
  #dplyr::filter(term_name == "extracellular organelle") %>%
  ggplot2::ggplot() + 
  ggplot2::aes(y = reorder(gene, -log(logFC)), x = logFC, color = stage, size = -log(p_adj.loc)) + 
  ggplot2::geom_point() + 
  #ggplot2::scale_color_continuous(name = "-Log(p_adj.loc)") + 
  #ggplot2::scale_size_continuous("logFC") + 
  ggplot2::theme_classic() +
  ggplot2::facet_wrap(~term_name, scales = "free_y", ncol = 13) +
  ggplot2::theme(strip.text = ggplot2::element_text(size = 8))
  #ggplot2::xlab("-Log(adj. p-value)") + 
  #ggplot2::ylab("GO term") + 
  #ggplot2::ggtitle("GO enrichment - all cells")


levels(factor(gProfiler_df$term_name))
table(gProfiler_df$term_name,gProfiler_df$term_size,grade)
n <- gProfiler_df %>% select(term_name, term_size,stage,cluster_id) %>% distinct() %>% arrange(term_size) %>% arrange(stage)

write.csv(table, paste0(dir_out,"table.csv"))
write.csv(RNAlistRDS005_df, paste0(dir_out,"RNAlistRDS005_df_Tan_AveExpr18.53202.csv"))


```







