n_cores: 12

memory:
  medium: 150000 #100000 was oom
  large: 190000

cell_populations:
  medium: ["lymphocyte","myeloid"]
  large: ["endothelial","epithelial"]

min_n_cells:
  medium: 50
  large: 50

threshold_pval_adj: 0.05




