use-conda: true
cores: 16
snakefile: "/home/duempelmann/analysis-projects/ENDO/E044/A030/major_celltypes_Tan/Snakefile"
conda-prefix: "/home/common/conda_envs/snakemake"
directory: "/home/common/data/output/projects/ENDO/E044/A030/major_celltypes_Tan/"
cluster-sync: "/home/common/bin/submit_job.sh"
latency-wait: 90
jobs: 2
conda-frontend: mamba
default-resources: mem_mb=200000
