project: "01_Atlas_generation_Integration"

##1 . Path to input
samples:
  global: "global"

##2. Path to output directories
norm_output_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/normalization/"
norm_output_list_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/normalization_list/"
integration_output_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/integration/"
mixing_metric_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/summary/"
logs_output_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/logs/"
subset_output_dir: "/endometriosis_endometrium_scRNA_atlas/01_Atlas_generation/Integration/setup_subsets/"

##3. Resources
ncores_norm: 5
memory_norm: 600000

ncores_seuratv3: 6
memory_seuratv3: 600000

ncores_cms: 5
memory_cms: 20000

## 4. params integration
n_features_integration_hvg: 3000
n_dimred_integration: 20
reference_dataset: "batch17"
